/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.awt.event.ActionEvent;

/**
 *
 * @author Felix
 */
public class GameWindow extends javax.swing.JPanel {

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextArea();
        Input = new javax.swing.JTextField();
        SysButton = new javax.swing.JToggleButton();
        ConButton = new javax.swing.JToggleButton();
        NavButton = new javax.swing.JToggleButton();
        SatButton = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(0, 0, 0));

        Title.setBackground(new java.awt.Color(0, 0, 0));
        Title.setForeground(new java.awt.Color(51, 133, 19));
        Title.setText("<html><pre>   _____   ___    __________   _____<br>  / ___/  /   |  /_  __/ __ \\ / ___/<br>  \\__ \\  / /| |   / / / / / / \\__ \\ <br> ___/ / / ___ |_ / / / /_/ / ___/ / <br>/____(_)_/  |_(_)_(_)\\____(_)____/  </html>");
        Title.setOpaque(true);

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setForeground(new java.awt.Color(51, 133, 19));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setFocusable(false);

        Output.setEditable(false);
        Output.setBackground(new java.awt.Color(0, 0, 0));
        Output.setColumns(20);
        Output.setForeground(new java.awt.Color(51, 133, 19));
        Output.setLineWrap(true);
        Output.setRows(5);
        Output.setText("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
        Output.setToolTipText("");
        Output.setWrapStyleWord(true);
        Output.setFocusable(false);
        jScrollPane2.setViewportView(Output);

        Input.setBackground(new java.awt.Color(0, 0, 0));
        Input.setForeground(new java.awt.Color(51, 133, 19));
        Input.setOpaque(false);
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        SysButton.setBackground(new java.awt.Color(0, 0, 0));
        SysButton.setForeground(new java.awt.Color(102, 102, 102));
        SysButton.setText("Sys");
        SysButton.setFocusPainted(false);
        SysButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SysButtonActionPerformed(evt);
            }
        });

        ConButton.setBackground(new java.awt.Color(0, 0, 0));
        ConButton.setForeground(new java.awt.Color(102, 102, 102));
        ConButton.setText("Con");
        ConButton.setFocusPainted(false);
        ConButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConButtonActionPerformed(evt);
            }
        });

        NavButton.setBackground(new java.awt.Color(0, 0, 0));
        NavButton.setForeground(new java.awt.Color(102, 102, 102));
        NavButton.setText("Nav");
        NavButton.setFocusPainted(false);
        NavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavButtonActionPerformed(evt);
            }
        });

        SatButton.setBackground(new java.awt.Color(0, 0, 0));
        SatButton.setForeground(new java.awt.Color(102, 102, 102));
        SatButton.setSelected(true);
        SatButton.setText("Sat");
        SatButton.setFocusPainted(false);
        SatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(Input)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NavButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SatButton)
                    .addComponent(SysButton)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SysButton)
                                    .addComponent(ConButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(SatButton)
                                .addGap(38, 38, 38))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NavButton)
                        .addGap(41, 41, 41)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed

        if (Interpreter.tryConnect)
            ConnectActionPerformed(evt);
        else if (Interpreter.tryCom)
             ComActionPerformed(evt);
        else
            InputActionPerformed(evt);
    }//GEN-LAST:event_ActionPerformed

    private void SatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatButtonActionPerformed
        SysButton.setSelected(false);
        NavButton.setSelected(false);
        ConButton.setSelected(false);
        Game.GameState = 1;
    }//GEN-LAST:event_SatButtonActionPerformed

    private void SysButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SysButtonActionPerformed
        SatButton.setSelected(false);
        NavButton.setSelected(false);
        ConButton.setSelected(false);
        Game.GameState = 2;
    }//GEN-LAST:event_SysButtonActionPerformed

    private void NavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavButtonActionPerformed
        SysButton.setSelected(false);
        SatButton.setSelected(false);
        ConButton.setSelected(false);
        Game.GameState = 3;
    }//GEN-LAST:event_NavButtonActionPerformed

    private void ConButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConButtonActionPerformed
        SysButton.setSelected(false);
        NavButton.setSelected(false);
        SatButton.setSelected(false);
        Game.GameState = 4;
    }//GEN-LAST:event_ConButtonActionPerformed
    private void InputActionPerformed(ActionEvent evt){
        String Text = this.Input.getText();
        this.Input.setText("");
        Interpreter.read(Text);
    }
    private void ConnectActionPerformed(ActionEvent evt){
        String Text = this.Input.getText();
        this.Input.setText("");
        Interpreter.Con(Text);
    }
    private void ComActionPerformed(ActionEvent evt){
        String Text = this.Input.getText();
        this.Input.setText("");
        Interpreter.Com(Text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ConButton;
    private javax.swing.JTextField Input;
    private javax.swing.JToggleButton NavButton;
    public static javax.swing.JTextArea Output;
    private javax.swing.JToggleButton SatButton;
    private javax.swing.JToggleButton SysButton;
    private javax.swing.JLabel Title;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
